### ISSUE TITLE
Request: YouTube Chat Compatibility for Stream Connect chat features

### ISSUE THREAD

**Issue by Kal-KrosswalkingKoboldsLLC** [CyanSMP64/NatDexExtension#3]
Currently the Stream Connect adds a command to Streamer Bot that can redirect appropriate commands to the Tracker. This command is compatible with YouTube chat as well:

<img width="367" alt="Screenshot 2024-04-15 152031" src="https://github.com/CyanSMP64/NatDexExtension/assets/167132428/e10d502c-7ea5-4aa7-90d6-e041399d4104">

At this time the Stream Connect feature is not set up to output to YouTube chat. I am not sure how this works through the tracker, but there is a sub action in streamer bot for outputting to YouTube Chat:

![image](https://github.com/CyanSMP64/NatDexExtension/assets/167132428/7dff632f-4391-41c2-a317-68c30e1d5b9b)

I am not sure what it would take to do this, but can you please add YouTube Chat compatibility for the tracker? Thank you!

**Comment by CyanSMP64** [comment]
This sounds like something that would be integrated into the core Tracker. Please create a new issue [here](https://github.com/besteon/Ironmon-Tracker) instead, or discuss in the #tracker-dev-chat channel of the IronMON Discord.
